#pv 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-vol
  namespace: bdovilla-namespace
spec: 
  storageClassName: mysql
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany 
  hostPath:
    path: "/mnt/mysql-vol1" 
---

#storegeclass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql
  namespace: bdovilla-namespace
provisioner: kubernetes.io/no-provisioner 
reclaimPolicy: Retain 
volumeBindingMode: WaitForFirstConsumer
---

#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: bdovilla-namespace
  labels:
    app: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - image: mysql:5.6  
        name: mysql-db1
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-db-volume1
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql.password 
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql.db
      volumes:
      - name: mysql-db-volume1
        persistentVolumeClaim:
           claimName: pvc-mysql-claim
---

#configmap
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: mysql-configmap 
  namespace: bdovilla-namespace
data: 
  mysql.password: "Eduardo93"
  mysql.db: "bdov"
---

#pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-claim
  namespace: bdovilla-namespace
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteMany
    requests:
      storage: 5Gi
---

#service
apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  namespace: bdovilla-namespace
spec:
  selector:
    app: mysql-server 
  ports:  
    - port: 5303 
      targetPort: 6379 
      protocol: TCP 
  type: LoadBalancer 